apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306             # Internal MySQL port
      targetPort: 3306        # Container's MySQL port

