apiVersion: v1
kind: Service
metadata:
  name: directory
spec:
  type: NodePort
  selector:
    app: directory
  ports:
    - protocol: TCP
      port: 389              # LDAP service port
      targetPort: 389         # Container's LDAP port
      nodePort: 30389         # Exposed on the node for LDAP access

